-*- mode: org; mode: visual-line; -*-
#+STARTUP: indent

* PRELUDE: CUSTOMISATION LOG
** [2022-02-04 Fri]
*** MORE CLOJURE

- See =init.el=: also turned on smartparens strict mode for Clojure (need to test it for ClojureScript - we may only need the one line).

** [2022-02-03 Thu]
*** CUSTOM / CLOJURE

- Added =personal/preload/init.el=: enabled rainbow delimiters (this might not work until clojure mode is enabled) and some customisation of Projectile.

** [2022-02-02 Wed]
*** SETUP

- Custom install: fork and then download/sync the =master= branch, link into =~/.emacs.d=.
- Launch Emacs, let it do its setup (make sure SSH is not blocked) - this all seems to be into external or gitignored folders so no Git changes to =master= seem to take place.
- Create and switch to =cassiel-custom= branch for any changes - starting with this =README= file.

*** CLOJURE

- Copy =sample/prelude-modules.el= to root directory, uncomment =prelude-clojure=. Evaluate the statement with =C-x C-e= - for some reason this file isn't loading on Emacs launch. Once the package installation is done, the loading seeme to persist - so I'm not sure we need to copy =prelude-modules.el= at all.
- Need Leiningen in the shell search path, obviously. Homebrew has it. Test with =lein repl=.
